version: '3'
services:
  postgres:
    image: postgres:10
    command: postgres -c 'max_connections=1000'
    restart: on-failure
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  dockerNet:
    driver: bridge

volumes:
  postgres:
    external: false